### ISSUE TITLE
Is the environment variable `CAP_Model::Parl_server` still used?

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#84]
I did a quick search, and the only reference to `Parl_server` I could see is in the Dockerfile itself where a default is set.

**Comment by SaschaAdler** [comment]
Yes, that's the one that reads `copresentation2` documents for parl-specific metadata so that the browse tree can be built.

As for the above, the following can definitely go away:

- `CAP_Model::Access::Derivative_password`
- `CAP_Model::Access::Presentation_download_mode`

I don't think the code is currently pointing to the `access-files` container for multi-page PDFs as of yet. Should it?

**Comment by RussellMcOrmond** [comment]
I am jumping the gun on `CAP_Model::Access::Download_container` as all the multi-page PDF files are still using ` canonicalDownload` field and not `canonicalDownloadExtension` as is used for the single-page PDF's.

Thank you.  We will clean up the multi-page PDF aspects once we get the new PDF's in place.

**Comment by RussellMcOrmond** [comment]
BTW:  Interesting how `CAP_Model::Parl_server` environment variable config works.

This is the `server` variable for a `Role::REST::Client` object that is the `package CAP::Model::Parl;`.
https://github.com/crkn-rcdr/cap/blob/main/CAP/lib/CAP/Model/Parl.pm

Probably good for @brittnylapierre to take a look and make sure that makes sense to her as well.
